-- local icons = {
--   Text = "",
--   Method = "",
--   Function = "",
--   Constructor = "",
--   Field = "",
--   Variable = "",
--   Class = "ﴯ",
--   Interface = "",
--   Module = "",
--   Property = "ﰠ",
--   Unit = "",
--   Value = "",
--   Enum = "",
--   Keyword = "",
--   Snippet = "",
--   Color = "",
--   File = "",
--   Reference = "",
--   Folder = "",
--   EnumMember = "",
--   Constant = "",
--   Struct = "",
--   Event = "",
--   Operator = "",
--   TypeParameter = ""
-- }

-- -- hrsh7th/nvim-cmp
-- local cmp = require("cmp")
-- cmp.setup({
--   sources = {
--     { name = "nvim_lsp", keyword_length = 1 },
--     { name = "buffer", keyword_length = 3 },
--     {
--       name = "path",
--       option = {
--         trailing_slash = true,
--         label_trailing_slash = true,
--       }
--     },
--   },
--   window = {
--     completion = cmp.config.window.bordered(),
--     documentation = cmp.config.window.bordered(),
--   },
--   formatting = {
--     fields = { "kind", "abbr" },
--     format = function(_, vim_item)
--       vim_item.kind = icons[vim_item.kind] or ""
--       return vim_item
--     end,
--   },
--   mapping = {
--     ["<Tab>"] = cmp.mapping(function(fallback)
--       if cmp.visible() then
--         cmp.select_next_item()
--       else
--         fallback()
--       end
--     end, { "i", "s" }),

--     ["<S-Tab>"] = cmp.mapping(function(fallback)
--       if cmp.visible() then
--         cmp.select_prev_item()
--       else
--         fallback()
--       end
--     end, { "i", "s" }),
--   },
-- })
